import type { RsvpResponseRecord } from "./rsvp-responses-types";

export const RSVP_RESPONSES_MOCK_DATA: RsvpResponseRecord[] = [
  {
    id: "response-ana-santos",
    guestName: "Ana Santos",
    email: "ana.santos@example.com",
    phone: "+63 917 100 0001",
    status: "attending",
    partySize: 3,
    companions: ["Marco Santos", "Lia Santos"],
    dietaryNotes: "No shellfish, please.",
    message: "Excited to celebrate with you both. We will arrive before the ceremony.",
    submittedAt: "2026-05-10T10:15:00+08:00",
    source: "public_rsvp_page",
  },
  {
    id: "response-pedro-reyes",
    guestName: "Pedro Reyes",
    email: "pedro.reyes@example.com",
    phone: "+63 917 100 0002",
    status: "not_attending",
    partySize: 1,
    companions: [],
    dietaryNotes: null,
    message: "Sending our love from Cebu. We will celebrate with you from afar.",
    submittedAt: "2026-05-11T15:42:00+08:00",
    source: "shared_link",
  },
  {
    id: "response-bianca-cruz",
    guestName: "Bianca Cruz",
    email: "bianca.cruz@example.com",
    phone: "+63 917 100 0003",
    status: "attending",
    partySize: 2,
    companions: ["Daniel Cruz"],
    dietaryNotes: null,
    message: null,
    submittedAt: "2026-05-12T09:05:00+08:00",
    source: "qr_code",
  },
  {
    id: "response-carla-lim",
    guestName: "Carla Lim",
    email: "carla.lim@example.com",
    phone: "+63 917 100 0004",
    status: "attending",
    partySize: 4,
    companions: ["Nico Lim", "Mia Lim", "Eli Lim"],
    dietaryNotes: "One vegetarian meal for Mia.",
    message: "We’re bringing the kids and they’re already counting down the days.",
    submittedAt: "2026-05-13T19:30:00+08:00",
    source: "public_rsvp_page",
  },
  {
    id: "response-miguel-garcia",
    guestName: "Miguel Garcia",
    email: "miguel.garcia@example.com",
    phone: "+63 917 100 0005",
    status: "not_attending",
    partySize: 1,
    companions: [],
    dietaryNotes: null,
    message: null,
    submittedAt: "2026-05-14T08:20:00+08:00",
    source: "shared_link",
  },
  {
    id: "response-elena-reyes",
    guestName: "Elena Reyes",
    email: "elena.reyes@example.com",
    phone: "+63 917 100 0006",
    status: "attending",
    partySize: 2,
    companions: ["Paolo Reyes"],
    dietaryNotes: "No nuts.",
    message: "Thank you for the invitation. We can’t wait to be there.",
    submittedAt: "2026-05-15T13:55:00+08:00",
    source: "qr_code",
  },
];
